### PR TITLE
refactor: removed unused function _run_strip_accents

### PR DESCRIPTION
**Pull request by ibrahim-601**
removed function _run_strip_accents from basic tokenizer which is never used.

### CODE REVIEW

**Comment by ibrahim-601** [comment]
Just a small refactor.

**Comment by sagorbrur** [comment]
Hi @ibrahim-601,
Thanks for the refactor. 
Can you do it in the branch bnlp_4_dev branch, it will be great. 
The present module will not be updated later because of the incompatibility with the newer version 4.0.0.
Please checkout to branch bnlp_4_dev and do the refactor. 

Thanks again.

**Comment by ibrahim-601** [comment]
Hi @sagorbrur ,

I have updated the merge request to be merged with branch bnlp_4_dev as you requested.

Thank you for mentioning the branch.

**Comment by sagorbrur** [comment]
maybe you did the changes to your master and send the pull request to bnlp_4_dev. Creating conflicting.
To resolve please do the changes in the bnlp_4_dev by checking out first and sending the pull request bnlp_4_dev branch. 
thanks again.

**Pull request closed without merging**
