### PR TITLE
apply pre-commit hook

### PR DESCRIPTION
**Pull request by menon92**

### CODE REVIEW

**Comment by menon92** [comment]
@sagorbrur I have added a pre-commit hook. Just use `pre-commit run --all-files` command to apply `pre-commit`
also need
```sh
pip install pre-commit
```

**Comment by sagorbrur** [comment]
@menon92 
Thank you for the pull request.
The initial build has failed for the stopwords JSON file.
I think at present no need to separate stopwords as a JSON file. Keep the stopwords method as it was and send pull request with pre-commit hook only. pre-commit would be a great help btw.
thanks again.

**Comment by menon92** [comment]
Okay

**Comment by menon92** [comment]
@sagorbrur I have updated the commit. So It will not use the JSON file.

**Comment by menon92** [comment]
After applying pre-commit the list is expended :)

**Comment by sagorbrur** [comment]
thanks. I will check details, modify if need and merge

**Review by sagorbrur — APPROVED** [review]
all changes are from pre-commit

**Pull request merged**
